export const ELEMENT_CATEGORIES = [
  { id: 'popular', label: 'Popular', virtual: true },
  { id: 'recent', label: 'Recently used', virtual: true },
  { id: 'favorites', label: 'Favorites', virtual: true },
  { id: 'flowers', label: 'Flowers' },
  { id: 'leaves', label: 'Leaves' },
  { id: 'floral-decorations', label: 'Floral' },
  { id: 'wedding', label: 'Wedding' },
  { id: 'festival', label: 'Festival' },
  { id: 'religious', label: 'Religious' },
  { id: 'birthday', label: 'Birthday' },
  { id: 'celebration', label: 'Celebration' },
  { id: 'diya', label: 'Diya' },
  { id: 'mandala', label: 'Mandala' },
  { id: 'indian-motifs', label: 'Indian Motifs' },
  { id: 'rangoli', label: 'Rangoli' },
  { id: 'peacock', label: 'Peacock' },
  { id: 'decorative', label: 'Decorative' },
  { id: 'borders', label: 'Borders' },
  { id: 'ribbons', label: 'Ribbons' },
  { id: 'badges', label: 'Badges' },
  { id: 'sparkles', label: 'Sparkles' },
  { id: 'abstract', label: 'Abstract' },
  { id: 'shapes', label: 'Shapes' },
  { id: 'icons', label: 'Icons' },
  { id: 'dividers', label: 'Dividers' },
];

export const FRAME_CATEGORIES = [
  { id: 'frames-popular', label: 'Popular', virtual: true },
  { id: 'frames-basic', label: 'Basic' },
  { id: 'frames-decorative', label: 'Decorative' },
  { id: 'frames-creative', label: 'Creative' },
  { id: 'frames-wedding', label: 'Wedding' },
  { id: 'frames-festival', label: 'Festival' },
  { id: 'frames-traditional', label: 'Traditional' },
  { id: 'frames-mandala', label: 'Mandala' },
];
